Tabby/urls.py
# Tabby URL Configuration
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.trips_index, name='index'),
    path(
        'trips/<int:trip_id>/', 
        views.trips_detail, 
        name='detail'
    ),
    path(
        'trips/create/', 
        views.trip_create, 
        name='trips_create'
    ),
    path(
        'trips/<int:pk>/update/',
        views.TripUpdate.as_view(),
        name='trips_update'
    ),
    path(
        'trips/<int:pk>/delete/',
        views.TripDelete.as_view(),
        name='trips_delete'
    ),
    path(
        'trips/<int:trip_id>/add_diary_entry/',
        views.add_diary_entry,
        name='add_diary_entry'
    ),
    path(
        'trips/<int:trip_id>/add_note/', 
        views.add_note, 
        name='add_note'
    ),
    path(
        'diary/<int:pk>/update/',
        views.DiaryUpdate.as_view(),
        name='diary_update'
    ),
    path(
        'diary/<int:pk>/delete/',
        views.DiaryDelete.as_view(),
        name='diary_delete'
    ),
    path(
        'note/<int:pk>/update/',
        views.NoteUpdate.as_view(),
        name='note_update'
    ),
    path(
        'note/<int:pk>/delete/',
        views.NoteDelete.as_view(),
        name='note_delete'
    ),
    path(
        'accounts/signup/', 
        views.signup, 
        name='signup'
    ),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField, TextField
from django.urls import reverse

# Create your models here.

class Trip(models.Model):
    title = models.CharField(max_length=100)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'trip_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for trip_id: {self.trip_id} @{self.url}"


class Diary_Entry(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    date = models.DateField()
    content = models.TextField()

    #def __str__(self):
        #return f"{self.get_content_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    content = TextField()

main_app/forms.py
from django.forms import ModelForm
from .models import Diary_Entry, Note, Trip

class Diary_EntryForm(ModelForm):
    class Meta:
        model = Diary_Entry
        fields = ['date', 'content']

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['content']

class TripForm(ModelForm):
    class Meta:
        model = Trip
        fields = ['title', 'to_location', 'from_location']

main_app/views.py
from django.forms.models import inlineformset_factory
from django.http.response import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Diary_Entry, Trip, Note, Photo
from .forms import Diary_EntryForm, NoteForm, TripForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
import boto3
import uuid

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'tabbyimages'

def trip_create(request):
  ModelForm = inlineformset_factory(Trip, Photo, exclude=['user'])
  if request.method == 'POST':
    form = TripForm(request.POST)
    if form.is_valid():
      trip = form.save(commit=False)
      trip.user = request.user
      trip.save()
      photo_file = request.FILES.get('photo-file', None)
      if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.
                                                     rfind('.'):]
        try:
          s3.upload_fileobj(photo_file, BUCKET, key)
          url = f"{S3_BASE_URL}{BUCKET}/{key}"
          Photo.objects.create(url=url, trip=trip)
        except:
          print('An error occurred uploading file to S3')
        return redirect('/')
  else:
    return render(request, 'main_app/trip_form.html')

class TripUpdate(LoginRequiredMixin, UpdateView):
  model = Trip
  fields = ['title', 'from_location', 'to_location']

class TripDelete(LoginRequiredMixin, DeleteView):
  model = Trip
  success_url = '/'

def trips_index(request):
  trips = Trip.objects.all()
  photos = Photo.objects.all()
  return render(request, 'home.html', {'trips': trips, 'photos': photos})

def trips_detail(request, trip_id):
  trip = Trip.objects.get(id=trip_id)
  diary_entry_form = Diary_EntryForm()
  note_form = NoteForm()
  return render(
      request, 'trips/detail.html', {
          'trip': trip,
          'diary_entry_form': diary_entry_form,
          'note_form': note_form
      }
  )

@login_required
def add_diary_entry(request, trip_id):
  form = Diary_EntryForm(request.POST)
  if form.is_valid():
    if Trip.objects.get(pk=trip_id).user == request.user:
      new_diary_entry = form.save(commit=False)
      new_diary_entry.trip_id = trip_id
      new_diary_entry.save()
    else:
      return HttpResponseForbidden()
  return redirect('detail', trip_id=trip_id)

@login_required
def add_note(request, trip_id):
  form = NoteForm(request.POST)
  if form.is_valid():
    new_note = form.save(commit=False)
    new_note.trip_id = trip_id
    new_note.user = request.user
    new_note.save()
  return redirect('detail', trip_id=trip_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('/')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class DiaryUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
  model = Diary_Entry
  fields = ['date', 'content']
  extra_context = {'diary_entry_form': Diary_EntryForm()}
  
  def test_func(self):
    return self.get_object().trip.user.id is self.request.user.id
  
  def get_success_url(self):
    return self.object.trip.get_absolute_url()

class DiaryDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
  model = Diary_Entry
  
  def test_func(self):
    return self.get_object().trip.user.id is self.request.user.id
  
  def get_success_url(self):
    return self.object.trip.get_absolute_url()

class NoteUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
  model = Note
  fields = ['content']
  extra_context = {'note_form': NoteForm}
  
  def test_func(self):
    return self.get_object().user.id is self.request.user.id
  
  def get_success_url(self):
    return self.object.trip.get_absolute_url()

class NoteDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
  model = Note
  
  def test_func(self):
    return self.get_object().user.id is self.request.user.id
  
  def get_success_url(self):
    return self.object.trip.get_absolute_url()

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tabby</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;500;800&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

main_app/templates/diary_entries/diary_entry_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="mainform">
  <nav id="formNav">
    <a href="/" class="CRUDButton">
      <div class="formNavIcon">
        <img
          id="formNavIconImage"
          src="{% static '/css/main_app/closeIcon.svg' %}"
          alt="Close Icon"
        />
      </div>
    </a>
  </nav>
  {% if object %}
  <h1 id="tripTitleDetail">Update Your Diary Entry</h1>
  {% else %}
  <h1 id="tripTitleDetail">Add Your Diary Entry</h1>
  {% endif %}
  <p id="tripUserNameDetail">Add the location and the photos for your trip.</p>
  <div class="formLineBreaker"></div>
  <form action="" method="post" class="formBlock">
    {% csrf_token %}
    {{ diary_entry_form.as_p }}
    <input type="submit" class="submitButton" value="Add Diary Entry"/>
  </form>
</main>
{% endblock content %}

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  {% include 'partials/header.html' %}
  <div class="generalContent">
    <div class="generalContentHeading">
      <p>Discover Other Trips</p>
    </div>
    <div class="generalContentBlock">
      {% for trip in trips %}
      <a id="tripBlock" href="/trips/{{ trip.id }}">
        
        <img
          id="tripImage"
          src="{{trip.photo_set.first.url}}"
        />
        
        <div class="tripImageShading"></div>
        <div class="tripContent">
          <div class="tripDetailBlock">
            <p id="tripName">{{ trip.title }}</p>
            <p id="tripUserName">{{ trip.user.username }}</p>   
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

main_app/templates/main_app/diary_entry_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="confirmCancelPage">
    <main class="confirmCancelMain">
        <h1 class="confirmCancelHeading">Are you sure you want to delete this diary entry?</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="confirmCancelBlock">
                <input type="submit" class="confirmSubmit" value="Yes - Delete!">
                <a href="{% url 'detail' diary_entry.trip.id %}" class="confirmCancel">Cancel</a>
            </div>
        </form>
    </main>
</div>

{% endblock content %}

main_app/templates/main_app/diary_entry_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="mainform">
  <nav id="formNav">
    <a href="{% url 'detail' diary_entry.trip.id %}" class="CRUDButton">
      <div class="formNavIcon">
        <img
          id="formNavIconImage"
          src="{% static '/css/main_app/closeIcon.svg' %}"
          alt="Close Icon"
        />
      </div>
    </a>
  </nav>
  {% if object %}
  <h1 id="tripTitleDetail">Update Your Diary Entry</h1>
  {% else %}
  <h1 id="tripTitleDetail">Add Your Diary Entry</h1>
  {% endif %}
  <div class="formLineBreaker"></div>
  <form action="" method="post" class="formBlock">
    {% csrf_token %}
    <!-- {{ diary_entry_form.as_p }} -->
    <p>
      <label for="id_date" class="dateLabel">Date:</label>
      <input type="text" name="date" required="" id="id_date">
    </p>
    <p>
      <label for="id_content" class="dateLabel">Content:</label>
      <textarea 
       name="content" 
       cols="40" 
       rows="10" 
       required="" 
       id="id_content"
       class="textAreaContent"
       placeholder="e.g. Your thoughts ..."
       ></textarea>
    </p>
    <input type="submit" class="submitButton" value="Add Diary Entry"/>
  </form>
</main>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
</script>
{% endblock content %}

main_app/templates/main_app/note_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="confirmCancelPage">
    <main class="confirmCancelMain">
        <h1 class="confirmCancelHeading">Are you sure you want to delete this comment?</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="confirmCancelBlock">
                <input type="submit" class="confirmSubmit" value="Yes - Delete!">
                <a href="{% url 'detail' note.trip.id %}" class="confirmCancel">Cancel</a>
            </div>
        </form>
    </main>
</div>
{% endblock content %}

main_app/templates/main_app/note_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="mainform">
  <nav id="formNav">
    <a href="{% url 'detail' note.trip.id %}" class="CRUDButton">
      <div class="formNavIcon">
        <img
          id="formNavIconImage"
          src="{% static '/css/main_app/closeIcon.svg' %}"
          alt="Close Icon"
        />
      </div>
    </a>
  </nav>
  {% if object %}
  <h1 id="tripTitleDetail">Update Your Comment</h1>
  {% else %}
  <h1 id="tripTitleDetail">Add Your Comment</h1>
  {% endif %}
  <div class="formLineBreaker"></div>
  <form action="" method="post" class="formBlock">
    {% csrf_token %}
    <!-- {{ note_form.as_p }} -->
    <p>
      <label for="id_content" class="dateLabel">Your Comment:</label>
      <textarea name="content" 
       cols="40" 
       rows="10" 
       required="" 
       id="id_content" 
       class="textAreaContent"
       placeholder="e.g. Your thoughts ..."
      ></textarea>
    </p>
    <input type="submit" class="submitButton" value="Update Note"/>
  </form>
</main>
{% endblock content %}

main_app/templates/main_app/trip_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="confirmCancelPage">
    <main class="confirmCancelMain">
        <h1 class="confirmCancelHeading">{{ object.title }}</h1>
        <br> <br>
        <h1 class="confirmCancelHeading">Are you sure you want to delete this trip?</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="confirmCancelBlock">
                <input type="submit" class="confirmSubmit" value="Yes - Delete!">
                <a href="{% url 'detail' trip.id %}" class="confirmCancel">Cancel</a>
            </div>
        </form>
    </main>
</div>

{% endblock content %}

main_app/templates/main_app/trip_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tabby</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;500;800&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <main class="mainform">
      <nav id="formNav">
        <a href="/" class="CRUDButton">
          <div class="formNavIcon">
            <img
              id="formNavIconImage"
              src="{% static '/css/main_app/closeIcon.svg' %}"
              alt="Close Icon"
            />
          </div>
        </a>
      </nav>
      {% if object %}
      <h1 id="tripTitleDetail">Update Your Trip</h1>
      {% else %}
      <h1 id="tripTitleDetail">Create Your Trip</h1>
      {% endif %}
      <p id="tripUserNameDetail">
        Add the location and the photos for your trip.
      </p>
      <div class="formLineBreaker"></div>

      <form
        action=""
        {% if not object %}
        enctype="multipart/form-data"
        {% endif %}
        method="post"
        class="formBlock"
      >
        {% csrf_token %}
        <label for="id_title">Title:</label>
        <input
          type="text"
          name="title"
          placeholder="e.g. Tokyo"
          maxlength="100"
          required=""
          id="id_title"
          class="formInput"
        />
        <div class="inputLine"></div>
        <label for="id_from_location">From location:</label>
        <input
          type="text"
          name="from_location"
          placeholder="e.g. Tokyo"
          maxlength="100"
          required=""
          id="id_from_location"
          class="formInput"
        />
        <div class="inputLine"></div>
        <label for="id_to_location">To location:</label>
        <input
          type="text"
          name="to_location"
          placeholder="e.g. Tokyo"
          maxlength="100"
          required=""
          id="id_to_location"
          class="formInput"
        />
        <div class="inputLine"></div>
        {% if not object %}
        <input type="file" name="photo-file" id="formFileInput" />
        {% endif %}
        <input type="submit" value="Submit!" class="submitButton" />
      </form>
    </main>
  </body>
</html>

main_app/templates/partials/header.html
{% load static %}
<header id="homeHeader">
  <div id="navHomeSection">
    <a id="navHomeButton" href="/">Tabby</a>
  </div>
  <div id="navOtherSection">
    {% if user.is_authenticated %}
    <div class="navOtherBlock">
      <a class="navOtherButton" href="{% url 'logout' %}">
        <p class="navOtherButtonText">Logout</p>
        <div class="navIcon">
          <img
            id="navIconImage"
            src="{% static '/css/main_app/exitIcon.svg' %}"
            alt="logout Icon"
          />
        </div>
      </a>
    </div>

    <div class="navOtherBlock">
      <a class="navOtherButton" href="{% url 'trips_create' %}">
        <p class="navOtherButtonText">Add Trip</p>
        <div class="navIcon">
          <img
            id="navIconImage"
            src="{% static '/css/main_app/Group.svg' %}"
            alt="Add Icon"
          />
        </div>
      </a>
    </div>
    {% else %}

    <div class="navOtherBlock">
      <a class="navOtherButton" href="{% url 'login' %}">
        <p class="navOtherButtonText">Login</p>
        <div class="navIcon">
          <img
            id="navIconImage"
            src="{% static '/css/main_app/loginIcon.svg' %}"
            alt="login Icon"
          />
        </div>
      </a>
    </div>
    <div class="navOtherBlock">
      <a class="navOtherButton" href="accounts/signup">
        <p class="navOtherButtonText">Sign Up</p>
        <div class="navIcon">
          <img
            id="navIconImage"
            src="{% static '/css/main_app/documentIcon.svg' %}"
            alt="login Icon"
          />
        </div>
      </a>
    </div>


    {% endif %}
  </div>
</header>

main_app/templates/trips/create.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="mainform">
  <nav id="formNav">
    <a href="/" class="CRUDButton">
      <div class="formNavIcon">
        <img
          id="formNavIconImage"
          src="{% static '/css/main_app/closeIcon.svg' %}"
          alt="Close Icon"
        />
      </div>
    </a>
  </nav>
  {% if object %}
  <h1 id="tripTitleDetail">Update Your Trip</h1>
  {% else %}
  <h1 id="tripTitleDetail">Create Your Trip</h1>
  {% endif %}
  <p id="tripUserNameDetail">Add the location and the photos for your trip.</p>
  <div class="formLineBreaker"></div>
  <form action="" method="post" class="formBlock">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    <input
      type="text"
      name="title"
      placeholder="e.g. Tokyo"
      maxlength="100"
      required=""
      id="id_title"
      class="formInput"
    />
    <div class="inputLine"></div>
    <label for="id_from_location">From location:</label>
    <input
      type="text"
      name="from_location"
      placeholder="e.g. Tokyo"
      maxlength="100"
      required=""
      id="id_from_location"
      class="formInput"
    />
    <div class="inputLine"></div>
    <label for="id_to_location">To location:</label>
    <input
      type="text"
      name="to_location"
      placeholder="e.g. Tokyo"
      maxlength="100"
      required=""
      id="id_to_location"
      class="formInput"
    />
    <div class="inputLine"></div>

    <input type="submit" value="Submit!" class="submitButton" />
  </form>
</main>
{% endblock content %}

main_app/templates/trips/detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

{% for photo in trip.photo_set.all %}
<img
  id="tripImageDetail"
  src="{{photo.url}}"
/>
{% endfor %}

<nav id="navDetail">
  <nav id="formNav">
    <a href="/" class="CRUDButton">
      <div class="formNavIcon">
        <img
          id="formNavIconImage"
          src="{% static '/css/main_app/closeIcon.svg' %}"
          alt="Close Icon"
        />
      </div>
    </a>
  </nav>
</nav>
<main id="mainDetail">
  <header id="headerSectionDetail">
    <div id="headerDetail">
      <h1 id="tripTitleDetail">{{ trip.title }}</h1>
      <p id="tripTravelDetail">{{ trip.from_location }} - {{ trip.to_location}}</p>
      <p id="tripUserNameDetail">{{ trip.user.username }}</p>
    </div>
    {% if user.id is trip.user_id %}
    <div id="headerCRUDSection">
      <a href="{% url 'trips_update' trip.id %}" class="CRUDButton">
        <div class="navIcon">
          <img
            id="navIconImage"
            src="{% static '/css/main_app/edit.svg' %}"
            alt="Add Icon"
          />
        </div>
      </a>
      <a href="{% url 'trips_delete' trip.id %}" class="CRUDButton">
        <div class="navIcon">
          <img
            id="navIconImage"
            src="{% static '/css/main_app/bin.svg' %}"
            alt="Add Icon"
          />
        </div>
      </a>
    </div>
    {% else %}
    {% endif %}
  </header>
  <div class="sectionBreaker"></div>
  <div class="journalHeader">
    <h3 class="diaryEntryHeading">User Diary Entries</h3>
  </div>
  {% if user.id is trip.user_id %}
  <form
    action="{% url 'add_diary_entry' trip.id %}"
    method="post"
    class="formBlock"
  >
    {% csrf_token %}  <!-- {{ diary_entry_form.as_p }} -->
    <p>
      <label for="id_date" class="dateLabel">Date:</label>
      <div class="modal datepicker-modal" id="modal-42246662-a16e-376e-2ac0-806364b2fa58" tabindex="0">
        <div class="modal-content datepicker-container">
          <div class="datepicker-date-display">
            <span class="year-text">2021</span>
            <span class="date-text">Thu, Jul 15</span>
          </div>
          <div class="datepicker-calendar-container">
            <div class="datepicker-calendar">
            </div>
            <div class="datepicker-footer">
              <button class="btn-flat datepicker-clear waves-effect" style="visibility: hidden;" type="button">
              </button>
              <div class="confirmation-btns">
                <button class="btn-flat datepicker-cancel waves-effect" type="button">Cancel</button>
                <button class="btn-flat datepicker-done waves-effect" type="button">Ok</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <input type="text" name="date" required="" id="id_date">
    </p>
    <p>
      <label for="id_content" class="dateLabel">Content:</label>
      <textarea name="content"
       cols="40"
       rows="10" 
       required="" 
       id="id_content" 
       class="textAreaContent" 
       placeholder="e.g. Your thoughts ..."
       ></textarea>
    </p>

    <input type="submit" class="noteSubmitButton" value="Add Diary Entry" />
  </form>
  {% else %}
  {% endif %}

  <div id="diaryContentBlock">
    {% for diary_entry in trip.diary_entry_set.all %}
    <div class="diaryBlock">
      <div id="noteSectionDetail">
        <div id="headerDetail">
          <p class="diaryBlockText">{{ diary_entry.date }}</p>
        </div>
        {% if user.id is trip.user_id %}
        <div id="headerCRUDSection">
          <a href="{%url 'diary_update' diary_entry.pk%}" class="CRUDButton">
            <div class="navIcon">
              <img
                id="navIconImage"
                src="{% static '/css/main_app/edit.svg' %}"
                alt="Edit"
              />
            </div>
          </a>
          <a href="{%url 'diary_delete' diary_entry.pk%}" class="CRUDButton">
            <div class="navIcon">
              <img
                id="navIconImage"
                src="{% static '/css/main_app/bin.svg' %}"
                alt="Delete"
              />
            </div>
          </a>
        </div>
        {% else %}
        {% endif %}
      </div>
      <p class="diaryBlockText">{{ diary_entry.content }}</p>
    </div>
    {% endfor %}
  </div>

  <div class="sectionBreaker"></div>
  <div class="journalHeader">
    <h3 class="diaryEntryHeading">Other user comments</h3>
  </div>


  <form action="{% url 'add_note' trip.id %}" method="post" class="formBlock">
    {% csrf_token %} <!-- {{ note_form.as_p }} -->
    <p>
      <label for="id_content" class="dateLabel">Your Comment:</label> 
      <textarea name="content" 
       cols="40" 
       rows="10" 
       required="" 
       id="id_content" 
       class="textAreaContent" 
       placeholder="e.g. Your thoughts ..." 
       spellcheck="false"
       ></textarea>
    </p>
    <input type="submit" class="noteSubmitButton" value="Add Comment" />
  </form>


  <div id="diaryContentBlock">
    {% for note in trip.note_set.all %}
    <div class="diaryBlock">
      <div id="noteSectionDetail">
        <div id="headerDetail">
          <p class="diaryBlockText">{{ note.user.username }}</p>
        </div>
        <div id="headerCRUDSection">
          {% if user.id is note.user_id %}
          <a href="{% url 'note_update' note.pk %}" class="CRUDButton">
            <div class="navIcon">
              <img
                id="navIconImage"
                src="{% static '/css/main_app/edit.svg' %}"
                alt="Edit Note"
              />
            </div>
          </a>
          <a href="{% url 'note_delete' note.pk %}" class="CRUDButton">
            <div class="navIcon">
              <img
                id="navIconImage"
                src="{% static '/css/main_app/bin.svg' %}"
                alt="Delete Note"
              />
            </div>
          </a>
          {% else %}
          {% endif %}
        </div>
      </div>
      <p class="diaryBlockText">{{ note.content }}</p>
    </div>
    {% endfor %}
  </div>
</main>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
</script>

{% endblock content %}